

extends: [standard]
plugins: [html]


rules:
    no-mixed-spaces-and-tabs        : [error]
    indent                          :
                                    - error
                                    - 4
                                    - SwitchCase          : 0
                                      VariableDeclarator  : { var : 1, let : 1, const : 1 }
    semi                            : [off, never]
    quotes                          : [error, single, avoid-escape]
    arrow-parens                    : [error, as-needed]
    operator-linebreak              : [error, before, { overrides : { "?" : after } }]
    # object literal can not be used in chrome 49
    comma-dangle                    : [off, always-multiline]
    prefer-const                    : [off]
    yoda                            : [off]
    no-new                          : [off]
    default-case                    : [off]
    one-var                         : [off]
    space-before-function-paren     : [off]
    space-before-blocks             : [off]
    no-multiple-empty-lines         : [off]
    no-multi-spaces                 : [off]
    keyword-spacing                 : [off]
    key-spacing                     : [off]
    comma-spacing                   : [off]
    space-infix-ops                 : [off]
    spaced-comment                  : [off]
    eol-last                        : [off]
